Fix scalar indexing using ForwardDIff
jonniedie/ComponentArrays.jl pull request #153
Opened 2022-07-22 02:19 UTC by MilkshakeForReal

Please note the issue always exists and is not recently introduced. 
```julia
using Lux, Random, NNlib, Zygote, CUDA, ComponentArrays
CUDA.allowscalar(false)
using ForwardDiff
model = Chain(Dense(2 => 4))
rng = Random.default_rng()
x = randn(rng, 2, 4) |> gpu
ps, st = Lux.setup(rng, model)
ps = ps |> ComponentArray |> gpu
st = st |> gpu
ForwardDiff.gradient(ps -> sum(first(model(, ps,st))), ps)

2022-07-23 19:44 UTC, MilkshakeForReal commented
The culprit is `ForwardDiff.Partials` wrapping a `Tuple`, which makes CUDA unhappy
```julia
julia> using CUDA

julia> CUDA.allowscalar(false)

julia> a = CUDA.rand(3)
3-element CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}:
 0.64399
 0.62868804
 0.14182384

julia> copyto!(a,(4,5,6))
ERROR: Scalar indexing is disallowed.
Invocation of setindex! resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore are only permitted from the REPL for prototyping purposes.
If you did intend to index this array, annotate the caller with @allowscalar.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] assertscalar(op::String)
   @ GPUArraysCore C:\Users\Luffy\.julia\packages\GPUArraysCore\rSIl2\src\GPUArraysCore.jl:78
 [3] setindex!
   @ C:\Users\Luffy\.julia\packages\GPUArrays\gok9K\src\host\indexing.jl:17 [inlined]
 [4] setindex!
   @ C:\Users\Luffy\.julia\packages\GPUArrays\gok9K\src\host\indexing.jl:24 [inlined]
 [5] copyto!(dest::CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, src::Tuple{Int64, Int64, Int64})
   @ Base .\abstractarray.jl:893
 [6] top-level scope
   @ REPL[30]:1
 [7] top-level scope
   @ C:\Users\Luffy\.julia\packages\CUDA\DfvRa\src\initialization.jl:52

```

2022-07-27 18:01 UTC, jonniedie commented
Hey, thanks for the PR. I'm not actually sure if this fixes anything, though, because the only non-whitespace change adds a method for something that already worked (see comment).

2022-07-27 18:01 UTC, jonniedie requested changes

2022-07-27 18:18 UTC, MilkshakeForReal commented on src/compat/forwarddiff.jl
> +end
Yeah, because scalar indexing is fine on the CPU. Did you read my description?

2022-07-27 19:24 UTC, MilkshakeForReal commented
I'm closing this since I will move it to Lux

2022-07-29 16:49 UTC, MilkshakeForReal commented
reopen this since gup testing is finally here.

2022-07-29 17:58 UTC, MilkshakeForReal commented on src/compat/forwarddiff.jl
> +end
Only dispatch on GPUComponentArray now

2022-07-29 20:20 UTC, jonniedie commented
I wonder if we can just make another general method for `copy to!` like [this](https://github.com/jonniedie/ComponentArrays.jl/blob/f3a1b6d9e6d1549f7513579632d66597067eb93b/src/similar_convert_copy.jl#L35) that `collect`s the second argument in the case where it’s not an `AbstractArray`. That way we wouldn’t need a new `Requires` entry.

2022-07-29 20:38 UTC, MilkshakeForReal commented
But we don't always need to collect. `Tuple` is fine on CPU for example and collecting makes it slow.

2022-07-29 21:01 UTC, MilkshakeForReal commented
And `ForwardDiff.Partials` is an `AbstractArray`, so...
```
julia> ForwardDiff.Partials <: AbstractArray
true
```

2022-07-30 01:26 UTC, jonniedie commented
Yeah, I’d ideally like to not collect stack allocated things. It was just a thought.

But this is weird. We’re already doing `getdata` on the ComponentArray for the default implementation of `copyto!`. Maybe this is an issue of `ForwardDiff.Partials` not doing the right thing?

2022-07-30 06:09 UTC, MilkshakeForReal commented
Yeah this is weird. `Forward.gradient` don't support native CUDA arrays. 
```julia
julia> ForwardDiff.gradient(sum, cu[1,2])
ERROR: Scalar indexing is disallowed.
Invocation of setindex! resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore are only permitted from the REPL for prototyping purposes.
If you did intend to index this array, annotate the caller with @allowscalar.
Stacktrace:
```
but `ForwardDiff.jacobian` does 
```julia
julia> ForwardDiff.jacobian(identity, cu[1,2])
2×2 CuArray{Int64, 2, CUDA.Mem.DeviceBuffer}:
 1  0
 0  1
```

So we should follow this and only support `ForwardDiff.jacobian` on GPU
```julia
julia> ps = ComponentArray(cu[1f0,2f0,3f0,4f0], Axis(a=1:2, b=3:4));

julia> ForwardDiff.jacobian(identity, ps)
ERROR: This object is not a GPU array
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:33
  [2] backend(#unused#::Type)
    @ GPUArrays C:\Users\Luffy\.julia\packages\GPUArrays\Hyss4\src\device\execution.jl:15
  [3] backend(x::Matrix{Float32})
```
This is easy since `jacobian` should return a `Matrix`

2022-07-30 23:43 UTC, jonniedie reviewed
Hm. I think I want to dig into this a little more because It seems like the other broadcasting changes should have fixed this. I’d like to not have to add another Requires entry and if this is something that can be solved upstream with a change to ForwardDiff, it would benefit other array wrapper packages.

2022-07-30 23:43 UTC, jonniedie commented on src/compat/gpuarrays.jl
> +const GPUComponentArray = ComponentArray{T,N,<:GPUArrays.AbstractGPUArray,Ax} where {T,N,Ax<:Tuple{Vararg{AbstractAxis}}}
Why?

2022-08-11 01:09 UTC, MilkshakeForReal commented
Closing this since we should have a better solution!

2022-08-11 01:09 UTC, closed without merging